language: java
jdk:
  - oraclejdk9

# Cache gradle
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

# Upload test coverage to Code Climate
env:
  global:
    - CC_TEST_REPORTER_ID=27a480bde8b3b5d221680476d0e47a37ff0b61856fc7b888bc4c7208e9b7e0e6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - gradle cobertura

after_script:
  - ./cc-test-reporter format-coverage -t cobertura build/reports/cobertura/coverage.xml
  - ./cc-test-reporter upload-coverage

# Automatic Github deploy of the gvs-ui jar for tagged commits
deploy:
  provider: releases
  api_key:
    secure: VQX5SUA4TLTfTnjN/nYRfNcXTxnksk3ghFwQBFCC7z6Cqnm5va7XuMe4k+PP49gYdjEhzTUt94Xadipxm8blwqz3bCMHtOhgFNn3cVp+Jv0OXGXcCtffs6NcJbhStTtZR6mJ8d6YYCMF/Rq9ocWu1De/QG/YSg0XlQn9qJzQy2c5PlXjeZh226j6lbGJM2cKL0hvD/wVGwmUHbE32C9qBNUUjuOBsKxWztT6cbNQrwH4ZEFu5VIPxZE1pyhjqYt2LOujjtj4o97WJQSpqIjbSMCkfYJZh2QCg9qPM8tdeR1LBKwjHvaiWhqRuMgCZFn9iJtytnvV8sK3SZAgHQ0A9+vcmRqCJ4MSSI1V4DkHnFlanvV27fFdM0neSydzZJWzhH2q9ChoaN2hevBfcFr5z3yuLYLQap03VqoAwsKL4+UPgtsVpEVAnoHWu6sVGuhF4viPlHgMzMqNHYTUmZtZgHyuSvP6eHbZvBMhV4XysOiKxHy8IAKMoLgOeDO08Rq3HS+Ss6Vrem8AUlZepzRd6l+Jf291yZdf+rxvwqBdaBcIVSnRlFM6jY8Pr1zH0vLoesx07bGRlxDbx1TXnkAJ1o+YcEyqd1GYsMYtBdu9inEiU2gtYbDW0WTHWw4dM0dDZUPzi0ejyDiMOhnpLJO3BUdDkevy8MDnqfBpibIfmpo=
  file: "build/libs/adv-root-1.0.jar"
  skip_cleanup: true
  on:
    tags: true
